# Generated by Django 4.1.7 on 2023-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='doctor',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star')], default='1 star', max_length=100),
        ),
    ]
