# Generated by Django 4.1.7 on 2023-04-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0003_alter_profile_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
    ]
