# Generated by Django 4.1.7 on 2023-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0004_remove_profile_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review',
            field=models.CharField(default='No review', max_length=525),
        ),
    ]
