# Generated by Django 4.1.7 on 2023-04-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0005_alter_profile_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review',
            field=models.TextField(default='No review', max_length=525),
        ),
    ]
