# Generated by Django 4.1.7 on 2023-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0007_order_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(default=330),
        ),
    ]
