# Generated by Django 4.1.7 on 2023-04-18 11:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bongapp', '0008_product_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime(2023, 4, 18, 16, 44, 15, 970330))),
                ('email', models.EmailField(default='ridhimansin@gmail.com', max_length=254)),
                ('description', models.CharField(default='no special request', max_length=250)),
                ('seats', models.CharField(choices=[('2', '2'), ('4', '4'), ('10', '10'), ('20', '3 star'), ('30+(buffet)', '30+(buffet)')], default='2', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
