# Generated by Django 4.1.7 on 2023-04-18 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 16, 45, 29, 320119)),
        ),
    ]
