# Generated by Django 4.1.7 on 2023-04-18 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0011_alter_booking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 23, 6, 21, 68530)),
        ),
    ]
