# Generated by Django 4.1.7 on 2023-04-18 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0012_alter_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name2',
            field=models.TextField(default='no name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 4, 18, 23, 9, 39, 441868)),
        ),
    ]
