# Generated by Django 4.1.7 on 2023-04-19 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0013_booking_name2_alter_booking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name2',
        ),
        migrations.AddField(
            model_name='booking',
            name='exp_time',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 10, 22, 51, 322822)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 10, 22, 51, 322822)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.TextField(default='no name'),
        ),
    ]
