# Generated by Django 5.0.2 on 2024-07-31 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0016_delete_order_delete_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 10, 33, 1, 666947)),
        ),
    ]
