# Generated by Django 5.0.2 on 2024-07-31 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0017_alter_booking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 19, 6, 59, 502456)),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='bongapp.product')),
            ],
        ),
    ]
