# Generated by Django 5.0.2 on 2024-07-31 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0021_alter_booking_day_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 20, 11, 24, 23539)),
        ),
    ]
