# Generated by Django 5.0.2 on 2024-08-02 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0024_remove_ordermodel_items_ordermodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 9, 48, 6, 444707)),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
