# Generated by Django 5.0.2 on 2024-08-02 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0025_ordermodel_state_alter_booking_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 10, 24, 26, 619718)),
        ),
    ]
