# Generated by Django 5.0.2 on 2024-08-02 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0028_alter_booking_day_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 21, 25, 4, 171072)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='No address', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='No state', max_length=111),
        ),
    ]
