# Generated by Django 5.0.2 on 2024-08-02 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0029_alter_booking_day_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 21, 26, 30, 100512)),
        ),
    ]
