# Generated by Django 5.0.2 on 2024-08-02 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0030_alter_booking_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='state1',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 21, 27, 1, 382046)),
        ),
    ]
