# Generated by Django 5.0.2 on 2024-08-02 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0031_rename_address_profile_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 21, 29, 0, 412366)),
        ),
    ]
