# Generated by Django 5.0.2 on 2024-08-03 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0034_profile_address_profile_state_alter_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Ready'), (3, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 11, 55, 44, 545932)),
        ),
    ]
