# Generated by Django 5.0.2 on 2024-08-03 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0036_ordermodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 21, 42, 34, 280987)),
        ),
    ]
