# Generated by Django 5.0.2 on 2024-08-04 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0037_remove_ordermodel_payment_status_alter_booking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 12, 17, 56, 722021)),
        ),
    ]
