# Generated by Django 5.0.2 on 2024-08-04 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0038_remove_ordermodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 13, 37, 19, 175056)),
        ),
    ]
