# Generated by Django 5.0.2 on 2024-08-05 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0041_alter_booking_day_alter_ordermodel_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='stripe_checkout_sessionid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 18, 6, 4, 439127)),
        ),
    ]
