# Generated by Django 5.0.2 on 2024-08-05 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0044_product_stripe_price_id_alter_booking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 18, 19, 28, 312076)),
        ),
    ]
