# Generated by Django 5.0.2 on 2024-08-09 16:26

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0050_groupmessage_file_alter_booking_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 21, 56, 2, 594351)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
