# Generated by Django 5.0.2 on 2024-08-12 07:10

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0057_alter_booking_day_alter_chatgroup_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='AirConditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 12, 40, 7, 851949)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
