# Generated by Django 5.0.2 on 2024-08-12 07:10

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0058_hall_airconditioning_alter_booking_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='AirConditioning',
            new_name='Stage',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 12, 40, 19, 994078)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='ammenity',
            field=models.CharField(choices=[('Wifi', 'Wifi'), ('Parking', 'Parking'), ('Air Conditioning', 'Air Conditioning')], default='', max_length=100),
        ),
    ]
