# Generated by Django 5.0.2 on 2024-08-13 11:40

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0063_alter_booking_day_alter_chatgroup_groupname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='Stage',
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 17, 10, 18, 185716)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='ammenity',
            field=models.CharField(choices=[('Buffet', 'Buffet'), ('Cafeteria-Style', 'Cafeteria-Style'), ('Pre-Set Service', 'Pre-Set Service'), ('Cocktail-Style', 'Cocktail-Style'), ('Cabaret', 'Cabaret'), ('Banquet-Style', 'Banquet-Style'), ('Dinner-Dance', 'Dinner-Dance'), ('Exhibition', 'Exhibition'), ('Plated', 'Plated'), ('Meeting-Style', 'Meeting-Style')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
