# Generated by Django 5.0.2 on 2024-08-13 11:46

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0064_remove_hall_stage_alter_booking_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='category',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Grand', 'Grand'), ('Deluxe', 'Deluxe')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 17, 16, 39, 56867)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
