# Generated by Django 5.0.2 on 2024-08-13 12:42

import datetime
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0067_remove_hall_ammenity_hallbookings_ammenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 18, 12, 42, 364525)),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
