# Generated by Django 5.0.2 on 2024-08-24 03:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0090_alter_chatgroup_groupname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/ojfe8l5ulh2cyuy1wuiv', upload_to='profile_pics/'),
        ),
    ]
