# Generated by Django 5.0.2 on 2024-08-24 03:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0091_alter_hallbookings_booking_id_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
