# Generated by Django 5.0.2 on 2024-08-24 09:36

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bongapp', '0095_alter_hallbookings_booking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourImageModel',
        ),
        migrations.DeleteModel(
            name='YourRawFileModel',
        ),
        migrations.DeleteModel(
            name='YourVideoModel',
        ),
        migrations.AlterField(
            model_name='hallbookings',
            name='booking_id',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/shop/Chicken-Biriyani_gzmwb3', upload_to='shop/'),
        ),
    ]
